volumes:
  common-redis:
    name: 'common-redis'

services:

  redis:
    image: bitnami/redis:${REDIS_IMAGE_TAG}
    env_file:
      - .envs/redis.env
    networks:
      common-net:
        aliases:
          - common-redis
    volumes:
      - common-redis:/bitnami
    container_name: common-redis

#  redis-commander:
#    image: rediscommander/redis-commander:latest
#    env_file:
#      - .envs/redis-commander.env
#    container_name: common-redis-commander
#    networks:
#      common-net:
#        aliases:
#          - common-redis-commander
